import { buildTheme } from './helpers.ts';

export default buildTheme({
	background: '#2e3440',
	foreground: '#d8dee9',
	caret: '#f8f8f0',
	selection: '#434c5e',
	lineHighlight: '#3b4252',
	gutterBackground: '#2e3440',
	gutterForeground: '#4c566a',
	matchingBracket: 'transparent',
	matchingBracketOutline: '#ffffff',
	comment: '#4c566a',
	atom: '#b48ead',
	number: '#b48ead',
	propertyName: '#8fbcbb',
	attribute: '#8fbcbb',
	keyword: '#81a1c1',
	string: '#a3be8c',
	variable: '#d8dee9',
	typeName: '#d8dee9',
	definition: '#8fbcbb',
	function: '#8fbcbb',
	bracket: '#81a1c1',
	tag: '#bf616a',
	heading: '#b48ead',
	link: '#b48ead',
	url: '#b48ead',
	invalid: '#bf616a',
	emphasis: '#d8dee9',
	strong: '#eceff4',
}, true);
