import { buildTheme } from './helpers.ts';

export default buildTheme({
	background: '#0a001f',
	foreground: '#f8f8f8',
	caret: '#ffffff',
	selection: '#27007a',
	lineHighlight: '#27282e',
	gutterBackground: '#0a001f',
	gutterForeground: '#f8f8f8',
	gutterBorder: '#aaaaaa',
	matchingBracket: 'transparent',
	matchingBracketOutline: 'grey',
	keyword: '#ffbd40',
	atom: '#6c8cd5',
	number: '#116644',
	definition: '#ffffff',
	variable: '#ffffff',
	typeName: '#dddddd',
	function: '#ffffff',
	comment: '#808080',
	string: '#9fee00',
	meta: '#ffff00',
	bracket: '#cccc77',
	tag: '#ffbd40',
	attribute: '#fff700',
	invalid: '#ff0000',
	heading: '#ffbd40',
	link: '#ffbd40',
	url: '#ffbd40',
	emphasis: '#f8f8f8',
	strong: '#ffffff',
}, true);
